title: Tûtie’s blog
author: Agnès Haasser
email: prenom.nom@gmail.com
github_username: tut-tuuut
twitter_username: tut_tuuut
description: Bienvenue.
markdown: kramdown
theme: minima
highlighter: pygments
url: http://tut-tuuut.github.io
permalink: /:year/:month/:day/:title.html
paginate: 5
paginate_path: "blog/page:num/"
excerpt_separator: "<!-- more -->"
header_pages:
  - index.html
  - cv.html
  - conferences.md
plugins:
  - jekyll-sitemap
  - jekyll-paginate
sass:
  sass_dir: css
  style: compressed
