name: Tûtie’s blog
markdown: kramdown
highlighter: pygments
url: http://tut-tuuut.github.io
permalink: /:year/:month/:day/:title.html
paginate: 15
paginate_path: "blog/page:num/"
sass:
    sass_dir: css
    style: compressed
